import re

with open('scratch/generate.py', 'r') as f:
    text = f.read()

# 1. Remove MIDI boxes from header
text = re.sub(r'juce::ComboBox midiInBox;\n\s*juce::ComboBox midiOutBox;\n', '', text)

# 2. Remove MIDI boxes from cpp
midi_cpp_regex = r'midiInBox\.setBounds\(630, 302, 120, 24\);.*?midiOutBox\.onChange = \[this\]\(\) \{.*?audioProcessor\.openMidiOutput\(devs\[idx\]\.identifier\);\n    \};\n'
text = re.sub(midi_cpp_regex, '', text, flags=re.DOTALL)

# 3. Fix width and height warning in cpp
text = text.replace('g.fillRoundedRectangle(x, y, width, height, 4.0f);', 'g.fillRoundedRectangle(x, y, w, h, 4.0f);')

# 4. Fix OSC3_FINE -1 in processor (wait, it's generated by Python in generate.py!)
# In generate.py: ("OSC3_FINE", "FINE", 28, "knob"),
# I will change 28 to -1
text = text.replace('("OSC3_FINE", "FINE", 28, "knob"),', '("OSC3_FINE", "FINE", -1, "knob"),')

# 5. Fix bounds checking in timerCallback
timer_loop_old = """    for (auto& cp : ccParams)
    {
        float hwVal = incomingCcValues[cp.ccNumber].exchange(-1.0f);"""
timer_loop_new = """    for (auto& cp : ccParams)
    {
        if (cp.ccNumber >= 0 && cp.ccNumber < 128) {
            float hwVal = incomingCcValues[cp.ccNumber].exchange(-1.0f);"""
text = text.replace(timer_loop_old, timer_loop_new)

timer_loop_end_old = """            if (auto* param = apvts.getParameter(cp.id))
            {
                param->setValueNotifyingHost(param->convertTo0to1(hwVal));
            }
        }
    }"""
timer_loop_end_new = """            if (auto* param = apvts.getParameter(cp.id))
            {
                param->setValueNotifyingHost(param->convertTo0to1(hwVal));
            }
        }
        }
    }"""
text = text.replace(timer_loop_end_old, timer_loop_end_new)

# 6. Fix bounds checking in processBlock
process_loop_old = """    for (auto& cp : ccParams)
    {
        if (cp.param != nullptr)"""
process_loop_new = """    for (auto& cp : ccParams)
    {
        if (cp.param != nullptr && cp.ccNumber >= 0 && cp.ccNumber < 128)"""
text = text.replace(process_loop_old, process_loop_new)

# 7. Fix Data Race by moving startTimerHz(30)
text = text.replace('    startTimerHz(30);\n', '')
text = re.sub(r'(syxParamMap\[102\] = "DLY_AMOUNT";\s*\})', r'\1', text) # Wait, need to properly insert it
text = text.replace('syxParamMap[102] = "DLY_AMOUNT";\n}', 'syxParamMap[102] = "DLY_AMOUNT";\n    startTimerHz(30);\n}')

with open('scratch/generate_clean.py', 'w') as f:
    f.write(text)

print("generate_clean.py created.")
